### ISSUE TITLE
LargeSk v1.2-Beta - ERROR ENABLING

### ISSUE THREAD

**Issue by DragonbornCommunity** [Nicofisi/LargeSk#2]
[00:25:25] [Server thread/INFO]: [LargeSk] Enabling LargeSk v1.2-Beta
[00:25:25] [Server thread/INFO]: [LargeSk 1.2-Beta] === ENABLE START ===
[00:25:25] [Server thread/ERROR]: Error occurred while enabling LargeSk v1.2-Beta (Is it up to date?)
com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'plugins\LargeSk': Token not allowed in path expression: '\' (Reserved character '\' is not allowed outside quotes) (you can double-quote this token if you really want it here)
    at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:155) ~[?:?]
    at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:74) ~[?:?]
    at com.typesafe.config.impl.PathParser.parsePath(PathParser.java:61) ~[?:?]
    at com.typesafe.config.impl.Path.newPath(Path.java:230) ~[?:?]
    at com.typesafe.config.impl.AbstractConfigValue.atPath(AbstractConfigValue.java:409) ~[?:?]
    at com.typesafe.config.impl.SimpleConfig.atPath(SimpleConfig.java:1023) ~[?:?]
    at pl.pickaxe.largesk.util.LargeConfig.loadBeta(LargeConfig.java:64) ~[?:?]
    at pl.pickaxe.largesk.LargeSk.onEnable(LargeSk.java:41) ~[?:?]

**Comment by sandor111** [comment]
Same error for me :(
